
import datetime
import time
local = time.strftime('%Y%m%d%H%M%S')
ftime = datetime.datetime.now().strftime('%Y%m%d%H%M%S%f')
fff = datetime.datetime.today()
ff = datetime.datetime.now()
time_stamp=str(int(time.time()))
# time_stamp=time.time() 
print(datetime.datetime.now())
print("---------------------------------------------------------------")
print(time.time())
print("---------------------------------------------------------------")
print(time.ctime())
print("---------------------------------------------------------------")
print(local)
print("---------------------------------------------------------------")
print(ftime)
print("---------------------------------------------------------------")
print(time_stamp)